print('Enter the name of cat 1:')
catName1 = input()
print('Enter the name of cat 2:')
catName1 = input()
print('Enter the name of cat 3:')
catName1 = input()
print('Enter the name of cat 4:')
catName1 = input()
print('Enter the name of cat 5:')
catName1 = input()
print('Enter the name of cat 6:')
catName1 = input()
print('The cat names are:')
print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' + catName6)
